packageName: net.manukagames.greeting.message
recipient:
  type: ConsoleRecipient
  supportClass: net.manukagames.greeting.message.ConsoleRecipientSupport
messages:
  greeting:
    context:
      _receiver: $Receiver
      senderName: String